name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        LOCKED_USERNAME: ${{ secrets.LOCKED_USERNAME }}
        LOCKED_PASSWORD: ${{ secrets.LOCKED_PASSWORD }}
      run: npx playwright test
    - uses: actions/upload-artifact@v5
      if: ${{ !cancelled() }}
      with:
        name: playwright-artifacts
        path: |
          playwright-report/
          test-results/
        if-no-files-found: ignore
        retention-days: 30
